// RBAC constants: stable permission & role identifiers plus role->permission mapping.
// Extend by adding new PERMISSIONS keys and including them in relevant ROLES_PERMISSIONS entries.
export const PERMISSIONS = {
  // Core / Dashboard
  VIEW_DASHBOARD: "VIEW:DASHBOARD",

  // Users (existing internal management)
  READ_USERS: "READ:USERS",
  CREATE_USERS: "CREATE:USERS",
  EDIT_USERS: "EDIT:USERS",
  DELETE_USERS: "DELETE:USERS",
  VIEW_USERS: "VIEW:USERS",

  // Roles
  VIEW_ROLES: "VIEW:ROLES",
  READ_ROLES: "READ:ROLES",
  CREATE_ROLES: "CREATE:ROLES",
  EDIT_ROLES: "EDIT:ROLES",
  DELETE_ROLES: "DELETE:ROLES",
  EDIT_ROLES_PERMISSIONS: "EDIT:ROLES_PERMISSIONS",

  EDIT_USER_PERMISSIONS: "EDIT:USER_PERMISSIONS",

  // Areas
  READ_AREAS: "READ:AREAS",
  CREATE_AREAS: "CREATE:AREAS",
  EDIT_AREAS: "EDIT:AREAS",
  DELETE_AREAS: "DELETE:AREAS",
  VIEW_AREAS: "VIEW:AREAS",

  // Cities
  READ_CITIES: "READ:CITIES",
  CREATE_CITIES: "CREATE:CITIES",
  EDIT_CITIES: "EDIT:CITIES",
  DELETE_CITIES: "DELETE:CITIES",
  VIEW_CITIES: "VIEW:CITIES",

  // Folding Types
  READ_FOLDING_TYPES: "READ:FOLDING_TYPES",
  CREATE_FOLDING_TYPES: "CREATE:FOLDING_TYPES",
  EDIT_FOLDING_TYPES: "EDIT:FOLDING_TYPES",
  DELETE_FOLDING_TYPES: "DELETE:FOLDING_TYPES",
  VIEW_FOLDING_TYPES: "VIEW:FOLDING_TYPES",

  // Services
  READ_SERVICES: "READ:SERVICES",
  CREATE_SERVICES: "CREATE:SERVICES",
  EDIT_SERVICES: "EDIT:SERVICES",
  DELETE_SERVICES: "DELETE:SERVICES",
  VIEW_SERVICES: "VIEW:SERVICES",

  // Remarks
  READ_REMARKS: "READ_REMARKS",
  CREATE_REMARKS: "CREATE_REMARKS",
  EDIT_REMARKS: "EDIT_REMARKS",
  DELETE_REMARKS: "DELETE_REMARKS",
  VIEW_REMARKS: "VIEW_REMARKS",

  // Works
  READ_WORKS: "READ_WORKS",
  CREATE_WORKS: "CREATE_WORKS",
  EDIT_WORKS: "EDIT_WORKS",
  DELETE_WORKS: "DELETE_WORKS",
  VIEW_WORKS: "VIEW_WORKS",

  // Layers
  READ_LAYERS: "READ_LAYERS",
  CREATE_LAYERS: "CREATE_LAYERS",
  EDIT_LAYERS: "EDIT_LAYERS",
  DELETE_LAYERS: "DELETE_LAYERS",
  VIEW_LAYERS: "VIEW_LAYERS",
} as const;

export const PERMISSION_GROUPS: {
  key: string;
  label: string;
  permissions: string[];
}[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    permissions: [PERMISSIONS.VIEW_DASHBOARD],
  },
  {
    key: "users",
    label: "Users",
    permissions: [
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.READ_USERS,
      PERMISSIONS.CREATE_USERS,
      PERMISSIONS.EDIT_USERS,
      PERMISSIONS.DELETE_USERS,
      PERMISSIONS.EDIT_USER_PERMISSIONS,
    ],
  },
  {
    key: "roles",
    label: "Roles",
    permissions: [
      PERMISSIONS.VIEW_ROLES,
      PERMISSIONS.READ_ROLES,
      PERMISSIONS.CREATE_ROLES,
      PERMISSIONS.EDIT_ROLES,
      PERMISSIONS.DELETE_ROLES,
      PERMISSIONS.EDIT_ROLES_PERMISSIONS,
    ],
  },
  {
    key: "areas",
    label: "Areas",
    permissions: [
      PERMISSIONS.VIEW_AREAS,
      PERMISSIONS.READ_AREAS,
      PERMISSIONS.CREATE_AREAS,
      PERMISSIONS.EDIT_AREAS,
      PERMISSIONS.DELETE_AREAS,
    ],
  },
  {
    key: "cities",
    label: "Cities",
    permissions: [
      PERMISSIONS.VIEW_CITIES,
      PERMISSIONS.READ_CITIES,
      PERMISSIONS.CREATE_CITIES,
      PERMISSIONS.EDIT_CITIES,
      PERMISSIONS.DELETE_CITIES,
    ],
  },
  {
    key: "folding_types",
    label: "Folding Types",
    permissions: [
      PERMISSIONS.VIEW_FOLDING_TYPES,
      PERMISSIONS.READ_FOLDING_TYPES,
      PERMISSIONS.CREATE_FOLDING_TYPES,
      PERMISSIONS.EDIT_FOLDING_TYPES,
      PERMISSIONS.DELETE_FOLDING_TYPES,
    ],
  },
  {
    key: "services",
    label: "Services",
    permissions: [
      PERMISSIONS.VIEW_SERVICES,
      PERMISSIONS.READ_SERVICES,
      PERMISSIONS.CREATE_SERVICES,
      PERMISSIONS.EDIT_SERVICES,
      PERMISSIONS.DELETE_SERVICES,
    ],
  },
  {
    key: "remarks",
    label: "Remarks",
    permissions: [
      PERMISSIONS.VIEW_REMARKS,
      PERMISSIONS.READ_REMARKS,
      PERMISSIONS.CREATE_REMARKS,
      PERMISSIONS.EDIT_REMARKS,
      PERMISSIONS.DELETE_REMARKS,
    ],
  },
  {
    key: "works",
    label: "Works",
    permissions: [
      PERMISSIONS.VIEW_WORKS,
      PERMISSIONS.READ_WORKS,
      PERMISSIONS.CREATE_WORKS,
      PERMISSIONS.EDIT_WORKS,
      PERMISSIONS.DELETE_WORKS,
    ],
  },
  {
    key: "layers",
    label: "Layers",
    permissions: [
      PERMISSIONS.VIEW_LAYERS,
      PERMISSIONS.READ_LAYERS,
      PERMISSIONS.CREATE_LAYERS,
      PERMISSIONS.EDIT_LAYERS,
      PERMISSIONS.DELETE_LAYERS,
    ],
  },
];

export const ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;
